name: CI

on: [push, pull_request] # on all pushes and PRs

jobs:
  ros1_bridge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["ros:melodic"]
    container:
      image: ${{ matrix.distro }}
    env:
      CCACHE_DIR: "/home/runner/.ccache"
    steps:
      - uses: actions/checkout@v2
      - name: ccache cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.distro }}-${{github.run_id}}
          restore-keys: |
            ccache-${{ matrix.distro }}
      - name: Build workspace
        run: |
          bash ./build.sh
      # - name: Run experiments
      #   run: |
      #     bash ./test_bridge.sh