name: CI

on: [push, pull_request] # on all pushes and PRs

jobs:
  metacontrol_experiments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["ros:melodic"]
        config: ["f1_v2_r2", "f1_v1_r2"]  # need to check how many configs can be run in parallel
    container:
      image: ${{ matrix.distro }}
    env:
      CCACHE_DIR: "/home/runner/.ccache"
    steps:
      - uses: actions/checkout@v2
      - name: ccache cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.distro }}-${{github.run_id}}
          restore-keys: |
            ccache-${{ matrix.distro }}
      - name: Build workspace
        run: |
          echo ${{ github.worspace }}
          echo $GITHUB_WORSPACE
          find . -name "*data*"
      # bash ./build.sh
      # - name: Run experiments
      #   run: |
      #     bash ./run_experiments.sh ${{ matrix.config }}
      # - name: 'Upload Artifact'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: my-artifact
      #     path: my_file.txt
      # /github/home/metacontrol_ws/src/metacontrol_experiments/data/log_Metacontrol_sim_14-07_58_24.csv
